# Generated by Django 4.2.7 on 2024-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
